# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  workflow_dispatch:
    inputs:
      productionRelease:
        description: 'Release Package - Draft'     
        default: false
      draftRelease:
        description: 'Release Package - Production'     
        default: false        
  push:
    branches: [ master ]
    tags:
      - "v*"
      - "-draft*"
      - "-rc*"    
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    env:
      filename: levelup-for-dynamics-365-power-apps
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Read package.json
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version        
    
    - run: npm ci

    - run: npm run pack
    
    - name: Create Draft Release ${{ env.filename }}-${{ steps.package-version.outputs.version }}
      id: create-draft-release
      uses: actions/create-release@v1
      if: contains(github.ref, '-draft') || github.event.inputs.draftRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ env.filename }}-${{ steps.package-version.outputs.version }}
        draft: true
        prerelease: true

    - name: Upload Draft Release Asset for Chrome ${{ env.filename }}-${{ steps.package-version.outputs.version }}-chrome.zip
      id: draft-release-zip-file
      uses: actions/upload-release-asset@v1
      if: steps.create-draft-release.conclusion == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-draft-release.outputs.upload_url }}
        asset_path: ./packages/${{ env.filename }}-${{ steps.package-version.outputs.version }}-chrome.zip
        asset_name: ${{ env.filename }}-${{ steps.package-version.outputs.version }}-chrome-DRAFT.zip
        asset_content_type: application/zip    
    
    - name: Create Release ${{ env.filename }}-${{ steps.package-version.outputs.version }}
      id: create-release
      uses: actions/create-release@v1
      if: contains(github.ref, 'refs/tags/v') || github.event.inputs.productionRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ env.filename }}-${{ steps.package-version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset for Chrome ${{ env.filename }}-${{ steps.package-version.outputs.version }}-chrome.zip
      id: release-zip-file
      uses: actions/upload-release-asset@v1
      if: steps.create-release.conclusion == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./packages/${{ env.filename }}-${{ steps.package-version.outputs.version }}-chrome.zip
        asset_name: ${{ env.filename }}-${{ steps.package-version.outputs.version }}-chrome.zip
        asset_content_type: application/zip
