# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    env:
      filename: Levelup-for-Dynamics-365-Power-Apps
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Read package.json
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version        
    
    - run: npm ci

    - run: npm run pack
    
    - name: Create Release ${{ env.filename }}-${{ steps.package-version.outputs.version }}
      id: create_release
      uses: actions/create-release@v1
      if: contains(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ env.filename }}-${{ steps.package-version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset for Chrome ${{ env.filename }}-${{ steps.package-version.outputs.version }}-chrome.zip
      id: release-zip-file
      uses: actions/upload-release-asset@v1
      if: steps.create_release.conclusion == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: packages/${{ env.filename }}-${{ steps.package-version.outputs.version }}-chrome.zip
        asset_name: ${{ env.filename }}-${{ steps.package-version.outputs.version }}-chrome.zip
        asset_content_type: application/zip